# Generated by Django 6.0.3 on 2026-03-29 20:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geozone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='геометрия геозоны')),
            ],
            options={
                'verbose_name': 'Геозона',
                'verbose_name_plural': 'Геозоны',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, verbose_name='Строковый идентификатор устройства')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('inside', models.BooleanField(verbose_name='Внутри геозоны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время проверки')),
                ('matched_geozone', models.ForeignKey(blank=True, help_text='Геозона, в которую попала точка (если есть)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='geozones.geozone', verbose_name='Геозона')),
            ],
            options={
                'verbose_name': 'Проверка точки',
                'verbose_name_plural': 'Проверки точек',
                'ordering': ['-created_at'],
            },
        ),
    ]
