# Generated by Django 6.0.3 on 2026-03-30 09:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geozones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='lon',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Геометрия геозоны'),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
