version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: axenta-web
    command: /app/docker/cmd_start_web.sh
    depends_on:
      - db
    env_file:
      - .env
    environment:
      RUN_DJANGO_MIGRATIONS: "true"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgis/postgis:16-3.4
    container_name: axenta-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: